# Configuração para que o Pytest e PytestDjango saiba onde que tá a settings do projeto
[pytest]
DJANGO_SETTINGS_MODULE = project.settings

# Onde o pytest vai tentar encontrar os testes
# test_*.py tests_*.py *_test.py é pq pode tá em modulos
python_files = tests.py test.py test_*.py tests_*.py *_test.py

# Permite passar configurações para o pytest
# --doctest-modules ativa o pytest para ler doctest
''' --strict-markers Marca o teste com uma categoria ex: teste lento 
e aceita só as marcas definidas agora em markers'''
addopts = 
  --doctest-modules
  --strict-markers
marks = 
  slow: Run tests are slow
  fast: Run tests are fast